name: PR Check CI
run-name: PR Check run by ${{ github.actor }}

# resources
# https://docs.github.com/en/actions/using-workflows#creating-a-workflow-file
# https://thatonegamedev.com/cpp/ci-cd-for-c-c-games-using-github-actions/
# https://github.com/florianvazelle/VulkanStarter/blob/main/.github/workflows/main.yml # uses conan and vulkan
# https://github.com/marketplace/actions/setup-vulkan-sdk
# https://www.youtube.com/watch?v=TWcmgyKrlFQ
on:
  #push:
  #  branches: [ "master" ] # trigger when pushing to master
  #pull_request:
  #  branches: [ "master" ] 
  workflow_dispatch: # allow manual runs 

jobs:
  build:

    runs-on: self-hosted # windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
          lfs: 'true' # when cloning / checkout, do so with git lfs tracked files?
    - name: Checkout LFS objects
      run: git lfs checkout # as per https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
    - name: configure-build-test workflow
      run: cmake --workflow --preset=vs2022r

